### ISSUE TITLE
Received S3 bucket credentials

### ISSUE THREAD

**Issue by bajo1207** [MDAIceland/WaterSecurity#6]
*Hello group Iceland*
*For the group assignment each group will have access to a personal S3 bucket. Within this bucket you can upload, read and write* *files. Please use this account only for the group assignment and not for other purposes. All activity on your account will be logged.*.....

Let me know if you need the credentials for some reason. 

I'll set up the automatic upload as in #5

**Comment by VasLem** [comment]
What is the state of this?

**Comment by bajo1207** [comment]
Was just an information issue, so can be closed.
